name: Отзыв или предложение
description: Оставьте замечание или идею по проекту
title: "[Отзыв] Краткое описание"
labels:
  - feedback
body:
  - type: dropdown
    id: project
    attributes:
      label: К какому проекту относится?
      options:
        - ТелеПост
        - RadicalMart Compare
        - RadicalMart Payment AtolPay
        - RadicalMart Payment Tochka
        - RadicalMart Quickicon Module
        - RadicalMart Shipping Courier
        - RadicalMart Shipping Pickup
        - RadicalMart LastView
        - RadicalMart CSVCart
        - RadicalMart Connect GooglePeopleAPI
        - RadicalMart Barcode
        - RadicalForm User Registration
        - RadicalForm PDF Create
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Опишите проблему или идею
      description: Расскажите, что именно хотите предложить или исправить.
      placeholder: |
        Например:
        - Ошибка на странице X...
        - Хочу добавить возможность...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Скриншоты, ссылки, примеры и т.д.
